In [10]:
import numpy as np
a = np.zeros(shape=(3,3))
try:
    for i in range(3):
        for j in range(3):
            a[i,j] = (int(input("only no:"))) 
    
    b = []
    i = 0
    for i in range(3):
        b.append(int(input("Enter a number")))
    c = np.multiply(a, b)
    print(c)
except:
    print("Invalid Data Entered")


[[1. 4. 9.]
 [1. 4. 9.]
 [1. 4. 9.]]
